#+TITLE: Pemahaman Jaringan
#+AUTHOR: Pramudya Arya Wicaksana
#+LATEX_CLASS: article
#+OPTIONS: toc:nil

* Halaman 4

Stand Alone Computer adalah personal computer yang hanya terdiri dari 1 unit
komputer yang berdiri sendiri dengan sumber daya sendiri. 1 unit PC terdiri
dari : monitor, cpu, keyboard, mouse, printer dan scanner. Sistem yang berdiri
sendiri.

* Halaman 5

1. Easiness = jaringan komputer dibuat dan dirancang agar pertukaran data
dilakukan dengan sangat mudah dan dapat dipahami oleh khalayak umum
2. No distance = jaringan komputer dibuat agar dapat mendekatkan, mempercepat
pertukan data dari suatu jarak yang jauh dengan waktu yang sangat singkat, artinya
jarak tidak berpengaruh dalam pertukaran data
3. Mobility = Pertukaran data dapat dilakukan dimana saja asalkan alat pertukaran
data telah mempuni
4. Efficiency = Jaringan komputer membuat pertukaran data menjadi lebih efisien,
mudah, murah, cepat, dan akurat

* Halaman 9

1. Biaya yang tinggi kemudian semakin tinggi lagi. pembangunan jaringan
meliputi berbagai aspek: pembelian hardware, software, biaya untuk
konsultasi perencanaan jaringan, kemudian biaya untuk jasa pembangunan
jaringan itu sendiri. Infestasi yang tinggi ini tentunya untuk perusahaan yang
besar dengan kebutuhan akan jaringan yang tinggi. Sedangkan untuk pengguna
rumahan biaya ini relatif kecil dan dapat ditekan. Tetapi dari awal juga network
harus dirancang sedemikian rupa sehingga tidak ada biaya overhead yang
semakin membengkak karena misi untuk pemenuhan kebutuhan akan jaringan
komputer ini.

2. Manajemen Perangkat keras Dan Administrasi sistem : Di suatu organisasi
perusahaan yang telah memiliki sistem, administrasi ini dirasakan merupakan
hal yang kecil, paling tidak apabila dibandingkan dengan besarnya biaya
pekerjaan dan biaya yang dikeluarkan pada tahap implementasi. Akan tetapi
hal ini merupakan tahapan yang paling penting. Karena Kesalahan pada point
ini dapat mengakibatkan peninjauan ulang bahkan konstruksi ulang jaringan.
Manajemen pemeliharaan ini bersifat berkelanjutan dan memerlukan seorang
IT profesional, yang telah mengerti benar akan tugasnya. Atau paling tidak
telah mengikuti training dan pelatihan jaringan yang bersifat khusus untuk
kebutuhan kantornya.
3. Sharing file yang tidak diinginkan : With the good comes the bad, ini selalu
merupakan hal yang umum berlaku (ambigu), kemudahan sharing file dalam
jaringan yang ditujukan untuk dipakai oleh orangorang tertentu, seringkali
mengakibatkan bocornya sharing folder dan dapat dibaca pula oleh orang lain
yang tidak berhak. Hal ini akan selalu terjadi apabila tidak diatur oleh
administrator jaringan.

4. Aplikasi virus dan metode hacking : hal-hal ini selalu menjadi momok yang
menakutkan bagi semua orang, mengakibatkan network down dan
berhentinya pekerjaan. Permasalahan ini bersifat klasik karena system yang
direncanakan secara tidak baik. Masalah ini akan dijelaskan lebih lanjut dalam
bab keamanan jaringan.

* Halaman 13

1. Software Jaringan

Software jaringan sendiri memiliki fungsi sebagai jaringan yang berfungsi
untuk mengetahui dan melihat tentang host mana yang terhubung antara satu
komputer dengan yang lain, melihat data yang sedang berjalan dan berbagai
fungsi lainnya. Pada intinya Software jaringan ini dipergunakan sebagai alat
untuk memantau dan melihat semua aktivitas yang ada pada komputer dan
berkaitan dengan jaringan. Berikut contoh contoh Software Jaringan :

A. Microsoft Network Monitor

Fungsi Microsoft Network Monitor :
- Melihat, Menangkat dan juga menganalisis segala proses yang ada
pada jaringan.
- Untuk mengatasi segala masalah yang ada pada jaringan ataupun
pada aplikasi jaringan.
- Menyediakan lebih dari 300 protokol proprietary public dan juga
Microsoft
- Mendeteksi lalu lintas modus promiscuous.
- Mengawasi Wireles yang sedang bekerja

B. Advanced IP Scanner

Fungsi Advanced IP Scanner :
- Mendeteksi jaringan pada komputer mulai dari jaringan nirkabel
hingga router WiFi.
- Menghubungkan komputer anda dengan layanan umum seperti HTTP,
FTP ataupun shared folder.
- Menghubungkan dengan mudah ke HTTP, FT dan juga shared folder.
- Mematikan ataupun meghidupkan komputer dengan lebih cepat.



C. Network View

Fungsi Network View :
- Mengetahui host mana saja yang aktif
- Memperlihatkan gambar host dan juga konektifitas antar host
- Melihat info jaringan secra lengkap
- Memodifikasi jaringan
- Melakukan scanning port mana saja yang aktif
- Melakukan PING pada jaringan

2. Software Aplikasi

Software Aplikasi yaitu suatu sistem atau program komputer yang memiliki
fungsi sebagai fasilitas digital yang membantu penggunanya menyelesaikan
tugas atau pekerjaan berupa pengolahan kata, gambar, angka, suara, dan
sebagainya. Tidak hanya itu, software aplkasi juga memiliki banyak fungsi lain
yang terbagi ke dalam banyak bidang atau kategori, seperti hiburan, bisnis,
edukasi, dan lain-lain. Selama kita masih menggunakan perangkat komputer,
maka secara otomatis kita tidak akan pernah terlepas dari penggunaan
software aplikasi dalam aktifitas komputerisasi sehari-hari kita. Berikut contoh
contoh Software Aplikasi :

A. Microsoft Office

Microsoft office adalah software aplikasi yang memiliki sejuta manfaat.
Software ini bisa membantumu untuk membuat berbagai jenis laporan.
Dari laporan sederhana, keuangan, hingga laporan menggunakan kreasi
multimedia yang menarik.
Keluarga Microsoft Office memiliki beragam jenis software aplikasi.
Mulai dari Microsoft Word untuk mengolah laporan, Microsoft
PowerPoint untuk mengelola presentasi, Microsoft Excel untuk
mengolah data yang melibatkan perhitungan dasar, Microsoft Acces
untuk merancang data besar, dan Microsoft Outlook untuk membaca
surat elektronik dan penjadwalan.

B. Google Chrome

Untuk software ini pasti kamu sudah sering menggunakannya. Google
Chrome adalah software yang digunakan untuk melakukan pencarian di
dunia maya. Sebuah peramban web sumber terbuka yang
dikembangkan Google dengan menggunakan mesin rendering WebKit.
Proyek sumber terbukanya dinamakan Chromium. Google Chrome
memiliki beberapa kelebihan yang membuat penggunanya betah
beberapa diantaranya simpel, cepat diakses, memiliki fitur menarik, dan
memiliki add-on yang lebih simpel dibanding dengan software
pencarian lainnya.

C. Adobe Illustrator

Adobe Illustrator merupakan salah satu program editor yang terkenal
dapat mempermudah pekerjaan kita. Adobe Illustrator memiliki resolusi
hasil akhir yang tinggi.
Program ini juga cocok untuk ilustrasi, logo, dan vector image lainnya.
Bahkan Adobe Illustrator juga memiliki garis yang jelas dan dibantu
dengan guide rules. Jika kamu memiliki file yang cukup besar, jangan
khawatir akan kerepotan, karena software ini juga mampu untuk load
file besar diatas 50 MB.

D. Corel Draw

Corel Draw terdengar lebih familiar dibanding Macromedia FreeHand.
Editor grafis ini dikembangkan dan dipasarkan oleh Corel Corporation of
Ottawa, Kanada. Corel Draw memiliki kelebihan hasil gambar berbasis
vektor yang baik, dukungan format import/export yang banyak,
kemudahan dalam penggunaan, dan memiliki banyak tool, baik
selection, editting dan pemberian efek.

E. Windows Internet Explorer

Mirip dengan Google Chrome, Windows Internet Explorer merupakan
sebuah peramban web dan perangkat lunak tak bebas yang gratis dari
Microsoft. Software ini juga disertakan dalam setiap rilis sistem operasi
Microsoft Windows dari 1995.
Windows Internet Explorer versi IE8, memiliki tampilan yang elegan dan
lebih menarik. Salah satu web senior ini memiliki banyak fitur yang
membantu meningkatkan kenyamanan dalam melakukan browsing.

3. Media Penyimpanan Data

Media penyimpanan adalah perangkat yang digunakan untuk menyimpan
berbagai macam data digital baik dalam bentuk dokumen, suara, gambar,
video, dan lain sebagainya. Seiring berkembangnya zaman, teknologi media
penyimpanan data pun kini telah mengalami perubahan. Berikut contoh
Media Penyimpanan Data :








A. Floppy Disk (Disket)

Jenis media penyimpanan data yang pertama adalah Floppy Disk Drive
(FDD) atau yang juga populer disebut disket. Ini adalah perangkat
penyimpanan data yang terbuat dari media penyimpanan magnetis
berbentuk lingkaran, yang ukurannya tipis. Media penyimpanan
magnetis itu disimpan dalam wadah/bodi berbentuk persegi atau persegi
panjang. Terdapat slot khusus di komputer untuk memasukkan disket,
yang disebut floppy disk drive. Disket sendiri digunakan sebagai media
penyimpanan untuk perangkat komputer. Disket sudah berkembang
sejak pertengahan tahun 1970 hingga 2000-an.

B. Hard disk Lihat
Jenis media penyimpanan data berikutnya adalah hard Disk adalah
perangkat keras (hardware) yang tertanam di perangkat komputer atau
laptop, yang bekerja sebagai media penyimpanan data. Singkatnya, Hard
Disk merupakan standar penyimpanan data untuk sebagian besar
perangkat PC. Karena bersifat permanen, maka data-data yang telah
disimpan di dalam hard disk tidak akan hilang, meskipun pengguna
mematikan perangkat PC mereka. Kapasitas hard disk sendiri umumnya
juga memiliki ukuran yang lumayan besar.

C. Hard disk eksternal

Hard disk eksternal pada dasarnya adalah hard disk yang tidak tertanam
di perangkat, bisa dilepas-pasang dengan mudah, dan bisa dibawa
kemana-mana. Ini merupakan media penyimpanan data yang mirip
seperti flash disk, hanya saja ukuran dan kapasitasnya lebih besar.
Dikatakan mirip karena hard disk eksternal juga sama-sama
menggunakan port USB. Ukuran hard disk eksternal pun terbilang cukup
tipis dibandingkan hard disk internal yang terpasang di perangkat
komputer atau laptop Meski begitu, kapasitas penyimpanan hard disk
eksternal sama-sama menawarkan ukuran yang lumayan besar hingga
hitungan Terabyte (1.000 gigabyte).

D. Flashdisk
Flashdisk merupakan perangkat penyimpanan data yang lumayan
populer. Dari waktu ke waktu, berbagai macam flashdisk sudah semakin
banyak bermunculan. Media penyimpan berjenis flash ini menggunakan
kabel interface berjenis USB (Universal Serial Bus), karena itu sering juga
disebut UFD (USB Flash Disk), atau sebutan lain seperti thumb drive.
Ukuran Flashdisk pun umumnya berkisar 50 x 15 x 6 mm. Sedangkan
kapasitas maksimumnya yang ada di pasar saat ini mencapai 1 TB (1.000
GB).


E. Memory card

Memory Card/kartu memori/SDcard merupakan aksesori yang berfungsi
untuk menyimpan berbagai jenis data digital seperti gambar, audio dan
video, dan lainnya. Kartu Memori umumnya dipakai oleh pengguna
smartphone, kamera digital, atau gadget teknologi lainnya. Banyak jenis
kartu memori yang beredar, seperti SD, SDHC, SDXC, MicroSD, dan

sebagainya. Kapasitas penyimpanan yang ditawarkan pun bermacam-
macam, mulai dari 2 GB hingga 512 GB (SDHC). Kapasitas maksimum SD
card yang bisa dijumpai di pasar saat ini adalah 1 TB. Untuk membuka
data yang tersimpan di kartu memori melalui perangkat komputer atau
laptop, pengguna harus memanfaatkan alat bernama Memory Card
Reader. Sebagian laptop sudah dibekali dengan pembaca kartu memori
ini. Sementara untuk smartphone, ada yang memiliki slot SDcard sebagai
memori tambahan, ada pula yang tidak.

* Halaman 24

Macam-Macam Topologi Jaringan Komputer

1. Topologi Bus
Topologi bus adalah topologi yang menggunakan kabel tunggal untuk media transmisi atau kabel pusat dimana semua client dan server terhubung. Sebelum menentukan topologi ini untuk membangun jaringan komputer, ada baiknya kita mengetahui kelebihan dan kekurangan dari topologi ini.

*Kelebihan*:
- Biaya instalasi yang sangat murah karena hanya menggunakan sedikit kabel.
- Penambahan client/workstation baru dapat dilakukan dengan sangat mudah.
- Topologi ini sederhana dan mudah di aplikasikan.

*Kekurangan*:
- Jika salah satu kabel pada topologi jaringan bus bermasalah atau putus, dapat mengganggu komputer workstation/client lain.
- Proses mengirim dan menerima data kurang efisien, biasanya terjadi tabrakan data pada topologi bus.
- Topologi yang jadul dan sulit untuk dikembangkan.

2. Topologi Star
Topologi star (bintang) merupakan salah satu bentuk topologi jaringan yang biasanya menggunakan switch / hub untuk menghubungkan client satu dengan client yang lainnya.

*Kelebihan*:
- Jika salah satu komputer bermasalah, jaringan pada topologi ini tetap berjalan dan tidak mempengaruhi komputer lainnya.
- Ini fleksibel.
- Tingkat keamanannya cukup baik dibandingkan topologi bus.
- Kemudahan dalam mendeteksi masalah sangat mudah jika terjadi kerusakan jaringan.

*Kekurangan*:
- Jika switch/hub sebagai titik pusat mengalami masalah, maka semua komputer yang terhubung dengan topologi ini akan mengalami masalah.
- Membutuhkan kabel yang cukup banyak, sehingga biayanya bisa dibilang cukup mahal.
- Jaringan sangat tergantung pada terminal pusat.

3. Topologi Cincin
Topologi ring atau biasa disebut topologi ring merupakan topologi jaringan yang menghubungkan satu komputer dengan komputer lainnya dalam suatu rangkaian melingkar, bentuknya hampir sama dengan cincin. Topologi ini biasanya hanya menggunakan LAN card untuk menghubungkan satu komputer dengan komputer lainnya.

*Kelebihan*:
- Performa lebih baik daripada topologi bus.
- Mudah diimplementasikan.
- Mengonfigurasi ulang dan memasang perangkat baru sangat mudah.
- Biaya pemasangan relatif murah.

*Kekurangan*:
- Kinerja komunikasi dari topologi ini dinilai dari jumlah titik atau node.
- Pemecahan masalah cukup rumit.
- Jika salah satu koneksi terputus, koneksi lainnya juga hilang.
- Pada topologi ini biasanya terjadi tabrakan data.






